import test from 'node:test';
import assert from 'node:assert/strict';
import path from 'node:path';
import { mkdtemp, readFile, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { configSchemaUrl, defaultConfig, loadConfig } from '../src/config.js';
import { initCommand } from '../src/commands/init.js';
import { parseArgs } from '../src/cli/args.js';

interface JsonSchemaProperty {
  default?: unknown;
  markdownDescription?: string;
}

interface JsonSchema {
  $id?: string;
  properties?: Record<string, JsonSchemaProperty>;
}

test('package init creates a concise schema-enabled .packagerc', async () => {
  const workspace = await mkdtemp(path.join(tmpdir(), 'package-init-'));
  try {
    await initCommand(workspace, false);
    const generated = await readFile(
      path.join(workspace, '.packagerc'),
      'utf8',
    );
    assert.match(
      generated,
      new RegExp(
        `^\\{\\n  "\\$schema": "${configSchemaUrl.replace(/[.*+?^${}()|[\\]\\\\]/g, '\\$&')}"`,
      ),
    );

    const parsed = JSON.parse(generated) as Record<string, unknown>;
    assert.deepEqual(Object.keys(parsed), [
      '$schema',
      'name',
      'strategy',
      'gitignore',
    ]);
    assert.equal(parsed.$schema, configSchemaUrl);
    assert.equal(parsed.name, defaultConfig.name);
    assert.equal(parsed.strategy, defaultConfig.strategy);
    assert.equal(parsed.gitignore, true);

    const loaded = await loadConfig(workspace);
    assert.equal(loaded.config.$schema, configSchemaUrl);
    assert.equal(loaded.config.root, defaultConfig.root);
    assert.equal(loaded.config.renameThreshold, defaultConfig.renameThreshold);
    assert.deepEqual(loaded.config.monorepo, defaultConfig.monorepo);

    const gitignore = await readFile(
      path.join(workspace, '.gitignore'),
      'utf8',
    );
    assert.equal(gitignore, '# Generated by @streetraceing/package\n*.zip\n');
  } finally {
    await rm(workspace, { recursive: true, force: true });
  }
});

test('package init --full creates the expanded template', async () => {
  const workspace = await mkdtemp(path.join(tmpdir(), 'package-init-full-'));
  try {
    await initCommand(workspace, { full: true, saveDeletedCache: false });
    const parsed = JSON.parse(
      await readFile(path.join(workspace, '.packagerc'), 'utf8'),
    ) as Record<string, unknown>;
    assert.equal(parsed.$schema, configSchemaUrl);
    assert.equal(parsed.root, defaultConfig.root);
    assert.equal(parsed.renameThreshold, defaultConfig.renameThreshold);
    assert.deepEqual(parsed.forceInclude, []);
    assert.deepEqual(parsed.beforeApply, []);
    assert.deepEqual(parsed.monorepo, defaultConfig.monorepo);
  } finally {
    await rm(workspace, { recursive: true, force: true });
  }
});

test('package init updates .gitignore without duplicating its generated block', async () => {
  const workspace = await mkdtemp(path.join(tmpdir(), 'package-init-ignore-'));
  try {
    await writeFile(
      path.join(workspace, '.gitignore'),
      'node_modules/\n*.zip\n',
      'utf8',
    );
    await initCommand(workspace, false, false);
    await initCommand(workspace, true, false);

    const gitignore = await readFile(
      path.join(workspace, '.gitignore'),
      'utf8',
    );
    assert.equal(
      gitignore,
      'node_modules/\n# Generated by @streetraceing/package\n*.zip\n',
    );
    assert.equal(
      gitignore.match(/# Generated by @streetraceing\/package/g)?.length,
      1,
    );
    assert.equal(gitignore.match(/^\*\.zip$/gm)?.length, 1);
  } finally {
    await rm(workspace, { recursive: true, force: true });
  }
});

test('published JSON Schema matches configuration defaults', async () => {
  const schema = JSON.parse(
    await readFile(path.resolve('schema.json'), 'utf8'),
  ) as JsonSchema;
  assert.equal(schema.$id, configSchemaUrl);

  const properties = schema.properties ?? {};
  for (const [key, value] of Object.entries(defaultConfig)) {
    assert.deepEqual(
      properties[key]?.default,
      value,
      `schema default for ${key}`,
    );
  }
  assert.equal(properties.$schema?.default, configSchemaUrl);
  for (const [key, property] of Object.entries(properties)) {
    assert.ok(
      property.markdownDescription?.includes('`'),
      `schema markdownDescription for ${key}`,
    );
  }
});

test('parses the explicit full rewrite apply flag', () => {
  const args = parseArgs(['apply', 'snapshot.zip', '--rewrite-all']);
  assert.equal(args.command, 'apply');
  assert.deepEqual(args.positionals, ['snapshot.zip']);
  assert.equal(args.rewriteAll, true);
});

test('parses force-selection and package-manager CLI overrides', () => {
  const args = parseArgs([
    'zip',
    '--force-include',
    'generated/required/**',
    '--force-ignore=secrets/**',
    '--package-manager',
    'pnpm',
    '--package-manager-ignore',
    '--package-manager-ignore-file',
    '.publishignore',
  ]);
  assert.deepEqual(args.configOverrides.forceInclude, [
    'generated/required/**',
  ]);
  assert.deepEqual(args.configOverrides.forceIgnore, ['secrets/**']);
  assert.equal(args.configOverrides.packageManager, 'pnpm');
  assert.equal(args.configOverrides.packageManagerIgnore, true);
  assert.equal(args.configOverrides.packageManagerIgnoreFile, '.publishignore');
});

test('parses monorepo workspace selection and graph expansion flags', () => {
  const args = parseArgs([
    'zip',
    '--workspace',
    '@acme/api',
    '--workspace=apps/web',
    '--workspace-pattern',
    'services/*',
    '--with-dependencies',
    '--with-dependents',
    '--no-root-files',
    '--monorepo',
  ]);
  assert.deepEqual(args.workspaceSelectors, ['@acme/api', 'apps/web']);
  assert.deepEqual(args.monorepoOverrides.workspacePatterns, ['services/*']);
  assert.equal(args.monorepoOverrides.includeDependencies, true);
  assert.equal(args.monorepoOverrides.includeDependents, true);
  assert.equal(args.monorepoOverrides.includeRootFiles, false);
  assert.equal(args.monorepoOverrides.mode, 'on');
});

test('configuration rejects options not declared by the schema', async () => {
  const workspace = await mkdtemp(path.join(tmpdir(), 'package-config-'));
  try {
    await writeFile(
      path.join(workspace, '.packagerc'),
      '{\n  \"unknownOption\": true\n}\n',
      'utf8',
    );
    await assert.rejects(
      loadConfig(workspace),
      /unknown option "unknownOption"/,
    );
  } finally {
    await rm(workspace, { recursive: true, force: true });
  }
});

test('configuration rejects JSON5-only syntax', async () => {
  const workspace = await mkdtemp(path.join(tmpdir(), 'package-json-only-'));
  try {
    await writeFile(
      path.join(workspace, '.packagerc'),
      `{
        // Comments are not valid JSON.
        "type": "zip",
      }\n`,
      'utf8',
    );
    await assert.rejects(
      loadConfig(workspace),
      /must use strict JSON: double-quoted keys and strings, no comments, and no trailing commas/,
    );
  } finally {
    await rm(workspace, { recursive: true, force: true });
  }
});

test('configuration rejects numeric strings', async () => {
  const workspace = await mkdtemp(path.join(tmpdir(), 'package-json-types-'));
  try {
    await writeFile(
      path.join(workspace, '.packagerc'),
      '{\n  "compressionLevel": "9"\n}\n',
      'utf8',
    );
    await assert.rejects(
      loadConfig(workspace),
      /compressionLevel must be an integer from 0 to 9/,
    );
  } finally {
    await rm(workspace, { recursive: true, force: true });
  }
});

test('configuration validates package hooks and apply cleanup settings', async () => {
  const workspace = await mkdtemp(path.join(tmpdir(), 'package-hooks-config-'));
  try {
    await writeFile(
      path.join(workspace, '.packagerc'),
      JSON.stringify(
        {
          beforePackage: 'npm run build',
          afterPackage: ['node scripts/report.mjs'],
          beforeApply: 'npm run migrate',
          afterApply: ['npm run prepare'],
          packageManager: 'pnpm',
          packageManagerIgnore: true,
          packageManagerIgnoreFile: '.publishignore',
          deletePackageOnApply: true,
          deleteSourcePackageOnApply: true,
          saveDeletedCache: false,
        },
        null,
        2,
      ),
      'utf8',
    );
    const loaded = await loadConfig(workspace);
    assert.deepEqual(loaded.config.beforePackage, ['npm run build']);
    assert.deepEqual(loaded.config.afterPackage, ['node scripts/report.mjs']);
    assert.deepEqual(loaded.config.beforeApply, ['npm run migrate']);
    assert.deepEqual(loaded.config.afterApply, ['npm run prepare']);
    assert.equal(loaded.config.packageManager, 'pnpm');
    assert.equal(loaded.config.packageManagerIgnore, true);
    assert.equal(loaded.config.packageManagerIgnoreFile, '.publishignore');
    assert.equal(loaded.config.deletePackageOnApply, true);
    assert.equal(loaded.config.deleteSourcePackageOnApply, true);
    assert.equal(loaded.config.saveDeletedCache, false);

    await writeFile(
      path.join(workspace, '.packagerc'),
      '{"beforePackage":42}\n',
      'utf8',
    );
    await assert.rejects(
      loadConfig(workspace),
      /beforePackage must be a non-empty string or an array of non-empty strings/,
    );
  } finally {
    await rm(workspace, { recursive: true, force: true });
  }
});

test('configuration instances do not share mutable default arrays', async () => {
  const first = await loadConfig(process.cwd());
  const second = await loadConfig(process.cwd());
  first.config.ignore.push('temporary/**');
  first.config.monorepo.shared.push('custom.json');
  assert.deepEqual(second.config.ignore, []);
  assert.equal(second.config.monorepo.shared.includes('custom.json'), false);
});

test('explicit config paths resolve root relative to the config file', async () => {
  const workspace = await mkdtemp(path.join(tmpdir(), 'package-config-base-'));
  try {
    await writeFile(
      path.join(workspace, 'project.packagerc'),
      '{"root":"./source","output":"../artifacts"}\n',
      'utf8',
    );
    const loaded = await loadConfig(
      path.join(workspace, 'unrelated'),
      '../project.packagerc',
    );
    const { resolveConfigPaths } = await import('../src/config.js');
    const resolved = resolveConfigPaths(loaded.config, loaded.configDirectory);
    assert.equal(resolved.root, path.join(workspace, 'source'));
    assert.equal(resolved.output, path.join(workspace, 'artifacts'));
  } finally {
    await rm(workspace, { recursive: true, force: true });
  }
});

test('CLI value options require exact option names', () => {
  assert.throws(
    () => parseArgs(['zip', '--cwdish', 'somewhere']),
    /Unknown option: --cwdish/,
  );
  assert.throws(
    () => parseArgs(['zip', '--compression-level=12']),
    /integer from 0 to 9/,
  );
  assert.throws(
    () => parseArgs(['zip', '--cwd', '--quiet']),
    /--cwd requires a value/,
  );
  assert.equal(parseArgs(['zip', '-o=release.zip']).output, 'release.zip');
});

test('CLI suggests a nearby command and parses init profiles', () => {
  assert.throws(() => parseArgs(['zpi']), /Did you mean zip/);
  assert.equal(parseArgs(['init', '--full']).initFull, true);
  assert.equal(parseArgs(['init', '--full', '--minimal']).initFull, false);
});

test('an explicit missing config is an error instead of silent defaults', async () => {
  await assert.rejects(
    loadConfig(process.cwd(), 'definitely-missing.packagerc'),
    /Configuration file does not exist/,
  );
});

test('package init respects concise strategy and gitignore choices', async () => {
  const workspace = await mkdtemp(path.join(tmpdir(), 'package-init-options-'));
  try {
    await initCommand(workspace, {
      strategy: 'walk',
      gitignore: false,
      updateGitignore: false,
      saveDeletedCache: false,
    });
    const parsed = JSON.parse(
      await readFile(path.join(workspace, '.packagerc'), 'utf8'),
    ) as Record<string, unknown>;
    assert.equal(parsed.strategy, 'walk');
    assert.equal(parsed.gitignore, false);
    await assert.rejects(
      readFile(path.join(workspace, '.gitignore')),
      /ENOENT/,
    );
  } finally {
    await rm(workspace, { recursive: true, force: true });
  }
});
