import test from 'node:test';
import assert from 'node:assert/strict';
import path from 'node:path';
import { mkdtemp, readFile, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { configSchemaUrl, defaultConfig, loadConfig } from '../src/config.js';
import { initCommand } from '../src/commands/meta.js';
import { parseArgs } from '../src/cli/args.js';

interface JsonSchemaProperty {
  default?: unknown;
  markdownDescription?: string;
}

interface JsonSchema {
  $id?: string;
  properties?: Record<string, JsonSchemaProperty>;
}

test('package init creates a schema-enabled .packagerc', async () => {
  const workspace = await mkdtemp(path.join(tmpdir(), 'package-init-'));
  try {
    await initCommand(workspace, false);
    const generated = await readFile(
      path.join(workspace, '.packagerc'),
      'utf8',
    );
    assert.match(
      generated,
      new RegExp(
        `^\\{\\n  "\\$schema": "${configSchemaUrl.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}"`,
      ),
    );

    const parsed = JSON.parse(generated) as Record<string, unknown>;
    assert.equal(parsed.$schema, configSchemaUrl);
    assert.equal(parsed.root, defaultConfig.root);
    assert.equal(parsed.renameThreshold, defaultConfig.renameThreshold);
    assert.deepEqual(parsed.beforePackage, []);
    assert.deepEqual(parsed.afterPackage, []);
    assert.deepEqual(parsed.beforeApply, []);
    assert.deepEqual(parsed.afterApply, []);
    assert.equal(parsed.deletePackageOnApply, false);
    assert.equal(parsed.deleteSourcePackageOnApply, false);
    assert.equal(parsed.saveDeletedCache, true);

    const loaded = await loadConfig(workspace);
    assert.equal(loaded.config.$schema, configSchemaUrl);
    assert.equal(loaded.config.gitignore, true);
    assert.equal(loaded.config.type, 'zip');

    const gitignore = await readFile(
      path.join(workspace, '.gitignore'),
      'utf8',
    );
    assert.equal(gitignore, '# Generated by @streetraceing/package\n*.zip\n');
  } finally {
    await rm(workspace, { recursive: true, force: true });
  }
});

test('package init updates .gitignore without duplicating its generated block', async () => {
  const workspace = await mkdtemp(path.join(tmpdir(), 'package-init-ignore-'));
  try {
    await writeFile(
      path.join(workspace, '.gitignore'),
      'node_modules/\n*.zip\n',
      'utf8',
    );
    await initCommand(workspace, false, false);
    await initCommand(workspace, true, false);

    const gitignore = await readFile(
      path.join(workspace, '.gitignore'),
      'utf8',
    );
    assert.equal(
      gitignore,
      'node_modules/\n# Generated by @streetraceing/package\n*.zip\n',
    );
    assert.equal(
      gitignore.match(/# Generated by @streetraceing\/package/g)?.length,
      1,
    );
    assert.equal(gitignore.match(/^\*\.zip$/gm)?.length, 1);
  } finally {
    await rm(workspace, { recursive: true, force: true });
  }
});

test('published JSON Schema matches configuration defaults', async () => {
  const schema = JSON.parse(
    await readFile(path.resolve('schema.json'), 'utf8'),
  ) as JsonSchema;
  assert.equal(schema.$id, configSchemaUrl);

  const properties = schema.properties ?? {};
  for (const [key, value] of Object.entries(defaultConfig)) {
    assert.deepEqual(
      properties[key]?.default,
      value,
      `schema default for ${key}`,
    );
  }
  assert.equal(properties.$schema?.default, configSchemaUrl);
  for (const [key, property] of Object.entries(properties)) {
    assert.ok(
      property.markdownDescription?.includes('`'),
      `schema markdownDescription for ${key}`,
    );
  }
});

test('parses the explicit full rewrite apply flag', () => {
  const args = parseArgs(['apply', 'snapshot.zip', '--rewrite-all']);
  assert.equal(args.command, 'apply');
  assert.deepEqual(args.positionals, ['snapshot.zip']);
  assert.equal(args.rewriteAll, true);
});

test('configuration rejects options not declared by the schema', async () => {
  const workspace = await mkdtemp(path.join(tmpdir(), 'package-config-'));
  try {
    await writeFile(
      path.join(workspace, '.packagerc'),
      '{\n  \"unknownOption\": true\n}\n',
      'utf8',
    );
    await assert.rejects(
      loadConfig(workspace),
      /unknown option "unknownOption"/,
    );
  } finally {
    await rm(workspace, { recursive: true, force: true });
  }
});

test('configuration rejects JSON5-only syntax', async () => {
  const workspace = await mkdtemp(path.join(tmpdir(), 'package-json-only-'));
  try {
    await writeFile(
      path.join(workspace, '.packagerc'),
      `{
        // Comments are not valid JSON.
        "type": "zip",
      }\n`,
      'utf8',
    );
    await assert.rejects(
      loadConfig(workspace),
      /must use strict JSON: double-quoted keys and strings, no comments, and no trailing commas/,
    );
  } finally {
    await rm(workspace, { recursive: true, force: true });
  }
});

test('configuration rejects numeric strings', async () => {
  const workspace = await mkdtemp(path.join(tmpdir(), 'package-json-types-'));
  try {
    await writeFile(
      path.join(workspace, '.packagerc'),
      '{\n  "compressionLevel": "9"\n}\n',
      'utf8',
    );
    await assert.rejects(
      loadConfig(workspace),
      /compressionLevel must be an integer from 0 to 9/,
    );
  } finally {
    await rm(workspace, { recursive: true, force: true });
  }
});

test('configuration validates package hooks and apply cleanup settings', async () => {
  const workspace = await mkdtemp(path.join(tmpdir(), 'package-hooks-config-'));
  try {
    await writeFile(
      path.join(workspace, '.packagerc'),
      JSON.stringify(
        {
          beforePackage: 'npm run build',
          afterPackage: ['node scripts/report.mjs'],
          beforeApply: 'npm run migrate',
          afterApply: ['npm run prepare'],
          deletePackageOnApply: true,
          deleteSourcePackageOnApply: true,
          saveDeletedCache: false,
        },
        null,
        2,
      ),
      'utf8',
    );
    const loaded = await loadConfig(workspace);
    assert.deepEqual(loaded.config.beforePackage, ['npm run build']);
    assert.deepEqual(loaded.config.afterPackage, ['node scripts/report.mjs']);
    assert.deepEqual(loaded.config.beforeApply, ['npm run migrate']);
    assert.deepEqual(loaded.config.afterApply, ['npm run prepare']);
    assert.equal(loaded.config.deletePackageOnApply, true);
    assert.equal(loaded.config.deleteSourcePackageOnApply, true);
    assert.equal(loaded.config.saveDeletedCache, false);

    await writeFile(
      path.join(workspace, '.packagerc'),
      '{"beforePackage":42}\n',
      'utf8',
    );
    await assert.rejects(
      loadConfig(workspace),
      /beforePackage must be a non-empty string or an array of non-empty strings/,
    );
  } finally {
    await rm(workspace, { recursive: true, force: true });
  }
});
