import path from 'node:path';
import { access, readFile } from 'node:fs/promises';
import { constants } from 'node:fs';
import { renderStarterConfig } from '../config.js';
import type { CollectionStrategy } from '../types.js';
import { PackageError } from '../errors.js';
import { writeFileAtomic } from '../util/fs.js';
import {
  DeletedCacheSession,
  reportDeletedCache,
} from '../util/deleted-cache.js';
import { color, divider, info, section, success } from '../util/terminal.js';

export interface InitCommandOptions {
  force?: boolean;
  full?: boolean;
  saveDeletedCache?: boolean;
  updateGitignore?: boolean;
  strategy?: CollectionStrategy;
  gitignore?: boolean;
  packageManager?: string;
}

async function initCacheEnabled(target: string): Promise<boolean> {
  try {
    const parsed = JSON.parse(await readFile(target, 'utf8')) as {
      saveDeletedCache?: unknown;
    };
    return parsed.saveDeletedCache !== false;
  } catch {
    return true;
  }
}

const generatedGitignoreMarker = '# Generated by @streetraceing/package';
const generatedGitignorePattern = '*.zip';

export function updateGitignoreContent(content: string): string {
  const newline = content.includes('\r\n') ? '\r\n' : '\n';
  const hadFinalNewline = content.endsWith('\n');
  const lines = content.length === 0 ? [] : content.split(/\r?\n/);
  if (hadFinalNewline && lines.at(-1) === '') lines.pop();

  const markerIndex = lines.findIndex(
    (line) => line.trim() === generatedGitignoreMarker,
  );
  const patternIndex = lines.findIndex(
    (line) => line.trim() === generatedGitignorePattern,
  );

  if (markerIndex !== -1 && patternIndex !== -1) return content;
  if (markerIndex !== -1) {
    lines.splice(markerIndex + 1, 0, generatedGitignorePattern);
  } else if (patternIndex !== -1) {
    lines.splice(patternIndex, 0, generatedGitignoreMarker);
  } else {
    if (lines.length > 0 && lines.at(-1) !== '') lines.push('');
    lines.push(generatedGitignoreMarker, generatedGitignorePattern);
  }
  return `${lines.join(newline)}${newline}`;
}

async function ensurePackageGitignore(
  cwd: string,
  deletedCache: DeletedCacheSession | undefined,
): Promise<void> {
  const target = path.resolve(cwd, '.gitignore');
  let current = '';
  let existed = false;
  try {
    current = await readFile(target, 'utf8');
    existed = true;
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code !== 'ENOENT') throw error;
  }

  const updated = updateGitignoreContent(current);
  if (updated === current) return;
  if (existed && deletedCache)
    await deletedCache.cachePath(target, 'replace-gitignore', '.gitignore');
  await writeFileAtomic(target, updated, 'utf8');
  success(`${existed ? 'Updated' : 'Created'} ${target}`);
}

function normalizeOptions(
  optionsOrForce: InitCommandOptions | boolean,
  legacySaveDeletedCache?: boolean,
): InitCommandOptions {
  if (typeof optionsOrForce === 'boolean') {
    return {
      force: optionsOrForce,
      saveDeletedCache: legacySaveDeletedCache,
    };
  }
  return optionsOrForce;
}

export async function initCommand(
  cwd: string,
  optionsOrForce: InitCommandOptions | boolean = {},
  legacySaveDeletedCache?: boolean,
): Promise<void> {
  const options = normalizeOptions(optionsOrForce, legacySaveDeletedCache);
  const target = path.resolve(cwd, '.packagerc');
  let exists = false;
  try {
    await access(target, constants.F_OK);
    exists = true;
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code !== 'ENOENT') throw error;
  }

  if (exists && !options.force) {
    throw new PackageError(
      `${target} already exists. Pass --force to overwrite it.`,
      'CONFIG_EXISTS',
    );
  }

  const deletedCacheEnabled =
    options.saveDeletedCache ??
    (exists ? await initCacheEnabled(target) : true);
  const deletedCache = deletedCacheEnabled
    ? new DeletedCacheSession(cwd, 'init')
    : undefined;
  if (exists && deletedCache)
    await deletedCache.cachePath(target, 'replace-config', '.packagerc');

  section('Project initialization');
  await writeFileAtomic(
    target,
    renderStarterConfig({
      full: options.full,
      strategy: options.strategy,
      gitignore: options.gitignore,
      packageManager: options.packageManager,
    }),
    'utf8',
  );
  success(`${exists ? 'Replaced' : 'Created'} ${target}`);

  const updateGitignore = options.updateGitignore ?? options.gitignore ?? true;
  if (updateGitignore) await ensurePackageGitignore(cwd, deletedCache);

  if (!options.full) {
    info('Config profile: concise starter; omitted options use safe defaults.');
    info(
      'Inspect defaults with package config --json; expand with package init --full.',
    );
  }
  reportDeletedCache(deletedCache);
  console.log(color.muted(divider(44)));
}
